module.exports = Object.freeze({
  APPS: {
    CUSTOMER: "CUSTOMER"
  },
  CUSTOMER_TYPES: {
    MANUFACTURER: "MANUFACTURER",
    DISTRIBUTOR: "DISTRIBUTOR",
    IMPORTER: "IMPORTER",
    TRADER: "TRADER",
    WHOLESALER: "WHOLESALER",
    RETAILER: "RETAILER"
  },
  PERMISSIONS: {
    CP_DASHBOARD_FULL: "CP_DASHBOARD_FULL",
    CP_INWARD_FULL: "CP_INWARD_FULL",
    CP_ORDER_FULL: "CP_ORDER_FULL",
    CP_WAREHOUSE_FULL: "CP_WAREHOUSE_FULL",
    CP_PRODUCT_FULL: "CP_PRODUCT_FULL",
    CP_RIDE_FULL: "CP_RIDE_FULL"
  },
  ROLES: {
    CUSTOMER_SUPER_ADMIN: "CUSTOMER_SUPER_ADMIN"
  },
  RIDE_STATUS: {
    UNASSIGNED: "UNASSIGNED",
    ASSIGNED: "ASSIGNED",
    INPROGRESS: "INPROGRESS",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED"
  },
  DISPATCH_ORDER: {
    STATUS: {
      PENDING: "Pending",
      PARTIALLY_FULFILLED: "Partially fulfilled",
      FULFILLED: "Fulfilled"
    }
  }
});
